name: Daily Increment

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 6,12,18,0 * * *'  # Run four times a day
  workflow_dispatch:  # Allows manual triggering

jobs:
  increment_number:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Increment Script
        run: |
          echo "Running increment script"
          python update_number.py

      - name: Randomize number of commits
        run: |
          # Generate a random number between 1 and 50 for the number of commits
          RANDOM_COMMITS=$((RANDOM % 50 + 1))
          echo "Number of commits to make: $RANDOM_COMMITS"

          # Loop to make random number of commits
          for i in $(seq 1 $RANDOM_COMMITS)
          do
            # Run the Python script to increment the number in number.txt
            python update_number.py

            # Commit and push the change
            git config --global user.name "awaisattiq"
            git config --global user.email "youremail@example.com"
            git add number.txt
            git commit -m "Daily increment update #$i"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/awaisattiq/NothingFancy.git
            sleep 5 # Add a short delay between commits
          done
